Update detect script to use new file location

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 # bin/use <build-dir>
 
-if [ -f $1/deps.edn ] && [ -f $1/config/compiler.edn ]; then
+if [ -f $1/deps.edn ] && [ -f $1/prod.cljs.edn ]; then
   echo "ClojureScript CLI" && exit 0
 else
-  (>&2 echo "Could not find a 'deps.edn' file! Please ensure it exists and is checked into Git.")
+  (>&2 echo "Could not find a 'deps.edn' file or a 'prod.cljs.edn' file! Please ensure it exists and is checked into Git.")
   exit 1
 fi
